#Tomcat端口号 默认是8080端口
server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1226422
    driver-class-name: com.mysql.cj.jdbc.Driver